---

# L3LS Fabric Values - update these values with caution, some changes could be disruptive.

fabric_name: DC1_FABRIC


# # Configure underlay routing protocol to be OSPF
# underlay_routing_protocol: OSPF

# Point to Point Network Summary range, assigned as /31 for each uplink interfaces
# Assign range larger then total [ spines * total potential leafs * 2 ]
underlay_p2p_network_summary: 192.16.255.0/24

# IP address range for evpn loopback for all switches in fabric, assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.17.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.17.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
      password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65101-65132
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 192.168.100.1/24
    DC1-SPINE2:
      id: 2
      mgmt_ip: 192.168.100.2/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65100
    spines: [ DC1-SPINE1, DC1-SPINE2 ]
    uplink_to_spine_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address : 00:dc:00:00:00:0a
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ all ]
        tags: [ web, app ]
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.100.3/24
          spine_interfaces: [ Ethernet1, Ethernet1 ]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 192.168.100.4/24
          spine_interfaces: [ Ethernet2, Ethernet2 ]
    DC1_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ Tenant_A, Tenant_B, Tenant_C ]
        # tenants: [ Tenant_A, Tenant_B, Tenant_C, tech_friday_demo ]
        tags: [ opzone, web, app, db, vmotion, nfs ]
      nodes:
        DC1-LEAF2A:
          id: 3
          mgmt_ip: 192.168.100.5/24
          spine_interfaces: [ Ethernet3, Ethernet3 ]
        DC1-LEAF2B:
          id: 4
          mgmt_ip: 192.168.100.6/24
          spine_interfaces: [ Ethernet4, Ethernet4 ]
    DC1_LEAF3:
      bgp_as: 65103
      filter:
        tenants: [ Tenant_A, Tenant_B, Tenant_C ]
        tags: [ opzone, web, app, db, vmotion, nfs ]
      nodes:
        DC1-LEAF3A:
          id: 5
          mgmt_ip: 192.168.100.7/24
          spine_interfaces: [ Ethernet5, Ethernet5 ]
        DC1-LEAF3B:
          id: 6
          mgmt_ip: 192.168.100.8/24
          spine_interfaces: [ Ethernet6, Ethernet6 ]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install, which is not supported in vEOS-LAB.

spine_bgp_defaults:
#  - update wait-for-convergence
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

leaf_bgp_defaults:
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

# Upodate p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

cv_configlets:
  containers:
    DC1_FABRIC:
      - DC1-CUSTOM_ALIASES
      - DC1-CUSTOM_TACACS