port_profiles:

  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"

  TENANT_A:
    mode: trunk
    vlans: "110"

  TENANT_B:
    mode: trunk
    vlans: "210-211"


servers:

  server01:
    rack: RackB
    adapters:
      - server_ports: [ Eth4, Eth5 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ DC1-LEAF1A, DC1-LEAF1B ]
        profile: TENANT_A
        port_channel:
          state: present
          description: PortChanne1
          mode: active

  server02:
    rack: RackB
    adapters:
      - server_ports: [ Eth2, Eth3 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ DC1-LEAF2A, DC1-LEAF2B ]
        profile: TENANT_B
        port_channel:
          state: present
          description: PortChanne1
          mode: active

  server03:
    rack: RackC
    adapters:
      - server_ports: [ Eth1, Eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ DC1-LEAF3A, DC1-LEAF3B ]
        profile: TENANT_A_B
        port_channel:
          state: present
          description: PortChanne1
          mode: active